version: "3.8"
   
services:
    web:
        build: .
        container_name: Weather_information
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        environment:
        - SQL_ENGINE=django.db.backends.postgresql_psycopg2
        - SQL_USER=postgres
        - SQL_PASSWORD=postgres
        - SQL_HOST=weather_db
        - SQL_PORT=5432
        - DATABASE=postgres
        depends_on:
            - weather_db

    weather_db:
        image: postgres:13.0-alpine
        volumes:
          - weather_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_DB=weather
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - "5432:5432"

volumes:
  weather_data:

    